#!/bin/bash
cd "$(dirname "$0")"
set -e
g++ checksum.cpp -o checksum "$@"
g++ field_checksum.cpp -o field_checksum "$@"
g++ gbid_checksum.cpp -o gbid_checksum "$@"
g++ collisions.cpp -o collisions "$@"
g++ field_collisions.cpp -o field_collisions "$@"
g++ gbid_collisions.cpp -o gbid_collisions "$@"
