#!/bin/bash
set -e
cd "$(dirname "$0")"
g++ -ggdb -O0 -o ./process "$@" process.cpp types/SkillKitDefinition.cpp types/SkillNodeMaybe.cpp types/te2a05745.cpp types/ActiveSkillEntry.cpp types/t9a30831a.cpp types/SkillNodeConnectionMaybe.cpp
