const fs = require('fs');

let prefix = {
  'm_': 'm_',
  'sno': 'sno',
};

let dict = {
  'a': 'a',
  'b': 'b',
  'c': 'c',
  'd': 'd',
  'e': 'e',
  'f': 'f',
  'g': 'g',
  'h': 'h',
  'i': 'i',
  'j': 'j',
  'k': 'k',
  'l': 'l',
  'm': 'm',
  'n': 'n',
  'o': 'o',
  'p': 'p',
  'q': 'q',
  'r': 'r',
  's': 's',
  't': 't',
  'u': 'u',
  'v': 'v',
  'w': 'w',
  'x': 'x',
  'y': 'y',
  'z': 'z',
  '0': '0',
  '1': '1',
  '2': '2',
  '3': '3',
  '4': '4',
  '5': '5',
  '6': '6',
  '7': '7',
  '8': '8',
  '9': '9',
  '_': '_',
  '2H': '2H',
  '2H': '2H',
  'Druid': 'Druid',
  'ab': 'ab',
  'Abilities': 'Abilities',
  'account': 'account',
  'Account': 'Account',
  'achievement': 'achievement',
  'Achievement': 'Achievement',
  'Achievements': 'Achievements',
  'Action': 'Action',
  'activity': 'activity',
  'actor': 'actor',
  'Actor': 'Actor',
  'Actors': 'Actors',
  'Add': 'Add',
  'Advance': 'Advance',
  'affix': 'affix',
  'Affix': 'Affix',
  'AGENTILE': 'AGENTILE',
  'ai': 'ai',
  'AI': 'AI',
  'All': 'All',
  'Alt': 'Alt',
  'ambient': 'ambient',
  'Amount': 'Amount',
  'Amulet': 'Amulet',
  'anim': 'anim',
  'Anim': 'Anim',
  'animation': 'animation',
  'Animation': 'Animation',
  'appearance': 'appearance',
  'area': 'area',
  'Area': 'Area',
  'Armor': 'Armor',
  'Arsenal': 'Arsenal',
  'aspect': 'aspect',
  'Assignment': 'Assignment',
  'Attribute': 'Attribute',
  'audio': 'audio',
  'Auto': 'Auto',
  'av': 'av',
  'awareness': 'awareness',
  'Axe': 'Axe',
  'Back': 'Back',
  'balance': 'balance',
  'Bands': 'Bands',
  'bank': 'bank',
  'Bank': 'Bank',
  'Bar': 'Bar',
  'Barbarian': 'Barbarian',
  'Barb': 'Barb',
  'basic': 'basic',
  'Bauble': 'Bauble',
  'behavior': 'behavior',
  'biome': 'biome',
  'Blank': 'Blank',
  'Blizzcon': 'Blizzcon',
  'Bludgeoning': 'Bludgeoning',
  'board': 'board',
  'Board': 'Board',
  'Body': 'Body',
  'bonus': 'bonus',
  'Book': 'Book',
  'boost': 'boost',
  'Boot': 'Boot',
  'Boots': 'Boots',
  'bounties': 'bounties',
  'Bounty': 'Bounty',
  'Bow': 'Bow',
  'Box': 'Box',
  'Breaking': 'Breaking',
  'Brightness': 'Brightness',
  'Browser': 'Browser',
  'Bubble': 'Bubble',
  'Buckets': 'Buckets',
  'Buff': 'Buff',
  'Buffs': 'Buffs',
  'Bug': 'Bug',
  'Button': 'Button',
  'Buttons': 'Buttons',
  'Cache': 'Cache',
  'Caches': 'Caches',
  'callback': 'callback',
  'Campaign': 'Campaign',
  'CAMP': 'CAMP',
  'Camps': 'Camps',
  'Canyon': 'Canyon',
  'Captions': 'Captions',
  'Categories': 'Categories',
  'Central': 'Central',
  'chain': 'chain',
  'challenge': 'challenge',
  'Character': 'Character',
  'Chat': 'Chat',
  'Checkout': 'Checkout',
  'Chest': 'Chest',
  'clan': 'clan',
  'Clan': 'Clan',
  'class': 'class',
  'Classes': 'Classes',
  'cloth': 'cloth',
  'Coast': 'Coast',
  'Co': 'Co',
  'code': 'code',
  'Codes': 'Codes',
  'Codex': 'Codex',
  'Collections': 'Collections',
  'collision': 'collision',
  'color': 'color',
  'Color': 'Color',
  'Combat': 'Combat',
  'Companions': 'Companions',
  'Complex': 'Complex',
  'component': 'component',
  'condition': 'condition',
  'Confirmation': 'Confirmation',
  'Connection': 'Connection',
  'Console': 'Console',
  'Consumable': 'Consumable',
  'Container': 'Container',
  'Content': 'Content',
  'context': 'context',
  'Context': 'Context',
  'controller': 'controller',
  'Controller': 'Controller',
  'Controls': 'Controls',
  'converation': 'converation',
  'conversation': 'conversation',
  'Conversation': 'Conversation',
  'Corbach': 'Corbach',
  'Cosmetic': 'Cosmetic',
  'Count': 'Count',
  'CPD': 'CPD',
  'crafter': 'crafter',
  'Crafting': 'Crafting',
  'Create': 'Create',
  'Credits': 'Credits',
  'Crossbow': 'Crossbow',
  'Currencies': 'Currencies',
  'Currency': 'Currency',
  'customization': 'customization',
  'Customization': 'Customization',
  'Cutscene': 'Cutscene',
  'Logo': 'Logo',
  'D4': 'D4',
  'Dagger': 'Dagger',
  'data': 'data',
  'Data': 'Data',
  'Death': 'Death',
  'Debug': 'Debug',
  'Default': 'Default',
  'definition': 'definition',
  'Demo': 'Demo',
  'demon': 'demon',
  'Demon': 'Demon',
  'Designer': 'Designer',
  'Dest': 'Dest',
  'Details': 'Details',
  'Dialog': 'Dialog',
  'Dialogs': 'Dialogs',
  'Disconnect': 'Disconnect',
  'Distribution': 'Distribution',
  'Door': 'Door',
  'Dose': 'Dose',
  'Down': 'Down',
  'DRLG': 'DRLG',
  'Drop': 'Drop',
  'Druid': 'Druid',
  'Dual': 'Dual',
  'dungeon': 'dungeon',
  'Dungeon': 'Dungeon',
  'dungeons': 'dungeons',
  'dye': 'dye',
  'Dynamic': 'Dynamic',
  'Ear': 'Ear',
  'East': 'East',
  'Eastern': 'Eastern',
  'Edit': 'Edit',
  'effect': 'effect',
  'Elemental': 'Elemental',
  'Elite': 'Elite',
  'Elixir': 'Elixir',
  'emblem': 'emblem',
  'emblems': 'emblems',
  'emote': 'emote',
  'emotes': 'emotes',
  'encounter': 'encounter',
  'End': 'End',
  'entry': 'entry',
  'Error': 'Error',
  'Essence': 'Essence',
  'event': 'event',
  'Event': 'Event',
  'Events': 'Events',
  'Exclusive': 'Exclusive',
  'Experience': 'Experience',
  'Expertise': 'Expertise',
  'explosion': 'explosion',
  'eye': 'eye',
  'face': 'face',
  'facial': 'facial',
  'Fade': 'Fade',
  'Fallen': 'Fallen',
  'Families': 'Families',
  'family': 'family',
  'Family': 'Family',
  'field': 'field',
  'First': 'First',
  'flag': 'flag',
  'Flats': 'Flats',
  'Floating': 'Floating',
  'Focus': 'Focus',
  'fog': 'fog',
  'Follower': 'Follower',
  'font': 'font',
  'Font': 'Font',
  'Footer': 'Footer',
  'Formula': 'Formula',
  'Formulas': 'Formulas',
  'Frac': 'Frac',
  'Friend': 'Friend',
  'Front': 'Front',
  'FTUE': 'FTUE',
  'Full': 'Full',
  'FX': 'FX',
  'Gale': 'Gale',
  'Gambling': 'Gambling',
  'game': 'game',
  'Game': 'Game',
  'Gear': 'Gear',
  'Gem': 'Gem',
  'gizmo': 'gizmo',
  'Glacier': 'Glacier',
  'global': 'global',
  'Global': 'Global',
  'globals': 'globals',
  'Globals': 'Globals',
  'Gloves': 'Gloves',
  'glyph': 'glyph',
  'Glyph': 'Glyph',
  'Gold': 'Gold',
  'Grid': 'Grid',
  'group': 'group',
  'Group': 'Group',
  'Groups': 'Groups',
  'hair': 'hair',
  'Hall': 'Hall',
  'Handed': 'Handed',
  'Hand': 'Hand',
  'Hardcore': 'Hardcore',
  'Hawe': 'Hawe',
  'health': 'health',
  'Health': 'Health',
  'Helm': 'Helm',
  'Help': 'Help',
  'Heroes': 'Heroes',
  'hero': 'hero',
  'Hero': 'Hero',
  'Hidden': 'Hidden',
  'Hireling': 'Hireling',
  'Hollow': 'Hollow',
  'Horse': 'Horse',
  'Hotkeys': 'Hotkeys',
  'houdini': 'houdini',
  'HUD': 'HUD',
  'ICamera': 'ICamera',
  'Icons': 'Icons',
  'IME': 'IME',
  'inactive': 'inactive',
  'Incense': 'Incense',
  'Indicator': 'Indicator',
  'Indicators': 'Indicators',
  'Indulgence': 'Indulgence',
  'In': 'In',
  'Inspect': 'Inspect',
  'Instance': 'Instance',
  'intensity': 'intensity',
  'Interact': 'Interact',
  'Interaction': 'Interaction',
  'Inventory': 'Inventory',
  'item': 'item',
  'Item': 'Item',
  'jewelry': 'jewelry',
  'Journey': 'Journey',
  'Kehj': 'Kehj',
  'Keyed': 'Keyed',
  'Key': 'Key',
  'Kick': 'Kick',
  'kit': 'kit',
  'Kyovashad': 'Kyovashad',
  'Labels': 'Labels',
  'Layer': 'Layer',
  'Layout': 'Layout',
  'Legend': 'Legend',
  'Legs': 'Legs',
  'level': 'level',
  'Level': 'Level',
  'levels': 'levels',
  'Levels': 'Levels',
  'light': 'light',
  'Light': 'Light',
  'Linking': 'Linking',
  'list': 'list',
  'List': 'List',
  'Loading': 'Loading',
  'Local': 'Local',
  'Loch': 'Loch',
  'Loc': 'Loc',
  'Login': 'Login',
  'Logout': 'Logout',
  'Loot': 'Loot',
  'Lorebook': 'Lorebook',
  'lore': 'lore',
  'Lore': 'Lore',
  'Lost': 'Lost',
  'loudness': 'loudness',
  'Low': 'Low',
  'Mace': 'Mace',
  'Mail': 'Mail',
  'Main': 'Main',
  'makeup': 'makeup',
  'Management': 'Management',
  'map': 'map',
  'Map': 'Map',
  'marker': 'marker',
  'markers': 'markers',
  'marking': 'marking',
  'Master': 'Master',
  'material': 'material',
  'Mat': 'Mat',
  'Mechanic': 'Mechanic',
  'Menu': 'Menu',
  'Menus': 'Menus',
  'Merge': 'Merge',
  'Meta': 'Meta',
  'mhershberg': 'mhershberg',
  'Minimap': 'Minimap',
  'Modal': 'Modal',
  'Mode': 'Mode',
  'Modifier': 'Modifier',
  'Modifiers': 'Modifiers',
  'monster': 'monster',
  'Monster': 'Monster',
  'Monsters': 'Monsters',
  'Mountain': 'Mountain',
  'Mount': 'Mount',
  'Mouse': 'Mouse',
  'Movement': 'Movement',
  'movie': 'movie',
  'Multi': 'Multi',
  'music': 'music',
  'Nameplate': 'Nameplate',
  'Names': 'Names',
  'Natural': 'Natural',
  'nav': 'nav',
  'Necromancer': 'Necromancer',
  'News': 'News',
  'nightmare': 'nightmare',
  'node': 'node',
  'none': 'none',
  'No': 'No',
  'normal': 'normal',
  'North': 'North',
  'Note': 'Note',
  'Notification': 'Notification',
  'Notifications': 'Notifications',
  'Notify': 'Notify',
  'NPCLook': 'NPCLook',
  'npc': 'npc',
  'npcs': 'npcs',
  'Objective': 'Objective',
  'observer': 'observer',
  'Offhand': 'Offhand',
  'Off': 'Off',
  'of': 'of',
  'Of': 'Of',
  'One': 'One',
  'On': 'On',
  'Op': 'Op',
  'Options': 'Options',
  'Order': 'Order',
  'Overlay': 'Overlay',
  'Over': 'Over',
  'OW': 'OW',
  'Panel': 'Panel',
  'paragon': 'paragon',
  'Paragon': 'Paragon',
  'param': 'param',
  'particle': 'particle',
  'Party': 'Party',
  'Pending': 'Pending',
  'Pet': 'Pet',
  'phase': 'phase',
  'physics': 'physics',
  'Picker': 'Picker',
  'Pick': 'Pick',
  'player': 'player',
  'Player': 'Player',
  'Playing': 'Playing',
  'Polearm': 'Polearm',
  'Pools': 'Pools',
  'Po': 'Po',
  'population': 'population',
  'Popup': 'Popup',
  'portals': 'portals',
  'Portraits': 'Portraits',
  'Potion': 'Potion',
  'potions': 'potions',
  'power': 'power',
  'Power': 'Power',
  'Prefab': 'Prefab',
  'Preorder': 'Preorder',
  'preset': 'preset',
  'Priorities': 'Priorities',
  'process': 'process',
  'product': 'product',
  'Profile': 'Profile',
  'progress': 'progress',
  'Progress': 'Progress',
  'Prompt': 'Prompt',
  'Prop': 'Prop',
  'Prototype': 'Prototype',
  'PS4': 'PS4',
  'pushed': 'pushed',
  'QA': 'QA',
  'QST': 'QST',
  'Quality': 'Quality',
  'quest': 'quest',
  'Quest': 'Quest',
  'quests': 'quests',
  'Radial': 'Radial',
  'Raeth': 'Raeth',
  'Ranged': 'Ranged',
  'Ranks': 'Ranks',
  'Ratings': 'Ratings',
  'Reagent': 'Reagent',
  'recipe': 'recipe',
  'Recipe': 'Recipe',
  'Region': 'Region',
  'Regions': 'Regions',
  'Render': 'Render',
  'Report': 'Report',
  'reputation': 'reputation',
  'requirement': 'requirement',
  'reverb': 'reverb',
  'reward': 'reward',
  'Reward': 'Reward',
  'Rewards': 'Rewards',
  'Ridge': 'Ridge',
  'Ring': 'Ring',
  'Roads': 'Roads',
  'Rogue': 'Rogue',
  'Roll': 'Roll',
  'rope': 'rope',
  'RTCDebug': 'RTCDebug',
  'Safe': 'Safe',
  'Salvage': 'Salvage',
  'Scaling': 'Scaling',
  'scene': 'scene',
  'Scheduler': 'Scheduler',
  'schedule': 'schedule',
  'Scoped': 'Scoped',
  'Scosglen': 'Scosglen',
  'Scos': 'Scos',
  'Screen': 'Screen',
  'Scripted': 'Scripted',
  'script': 'script',
  'scroll': 'scroll',
  'Scroll': 'Scroll',
  'Scythe': 'Scythe',
  'Select': 'Select',
  'Sequence': 'Sequence',
  'service': 'service',
  'set': 'set',
  'Set': 'Set',
  'settings': 'settings',
  'Settings': 'Settings',
  'shader': 'shader',
  'shake': 'shake',
  'shape': 'shape',
  'Shared': 'Shared',
  'Shield': 'Shield',
  'Shop': 'Shop',
  'Signed': 'Signed',
  'Signs': 'Signs',
  'Simple': 'Simple',
  'sim': 'sim',
  'Size': 'Size',
  'skill': 'skill',
  'Skill': 'Skill',
  'Skills': 'Skills',
  'Skip': 'Skip',
  'Slashing': 'Slashing',
  'Social': 'Social',
  'Socket': 'Socket',
  'Sorcerer': 'Sorcerer',
  'sound': 'sound',
  'South': 'South',
  'Spawning': 'Spawning',
  'Spawn': 'Spawn',
  'speaker': 'speaker',
  'Specializations': 'Specializations',
  'Spirit': 'Spirit',
  'Split': 'Split',
  'Stable': 'Stable',
  'Stack': 'Stack',
  'Staff': 'Staff',
  'stagger': 'stagger',
  'Stash': 'Stash',
  'States': 'States',
  'state': 'state',
  'State': 'State',
  'Step': 'Step',
  'store': 'store',
  'Store': 'Store',
  'story': 'story',
  'string': 'string',
  'Stronghold': 'Stronghold',
  'Styles': 'Styles',
  'style': 'style',
  'Style': 'Style',
  'sub': 'sub',
  'Subtitle': 'Subtitle',
  'Subzone': 'Subzone',
  'Summoning': 'Summoning',
  'surface': 'surface',
  'Survey': 'Survey',
  'Swap': 'Swap',
  'Sword': 'Sword',
  'Tables': 'Tables',
  'table': 'table',
  'Table': 'Table',
  'Tags': 'Tags',
  'Taiga': 'Taiga',
  'Talents': 'Talents',
  'Targeting': 'Targeting',
  'Target': 'Target',
  'templates': 'templates',
  'Template': 'Template',
  'territory': 'territory',
  'test': 'test',
  'Test': 'Test',
  'Text': 'Text',
  'texture': 'texture',
  'threshold': 'threshold',
  'Tiers': 'Tiers',
  'tiled': 'tiled',
  'tile': 'tile',
  'Time': 'Time',
  'Tip': 'Tip',
  'title': 'title',
  'Tome': 'Tome',
  'Tooltip': 'Tooltip',
  'Tool': 'Tool',
  'TOWN': 'TOWN',
  'tracked': 'tracked',
  'Tracker': 'Tracker',
  'Trade': 'Trade',
  'Trading': 'Trading',
  'trail': 'trail',
  'treasure': 'treasure',
  'Treasure': 'Treasure',
  'tree': 'tree',
  'Tree': 'Tree',
  'trigger': 'trigger',
  'Trophy': 'Trophy',
  'Tundra': 'Tundra',
  'tutorial': 'tutorial',
  'Tutorial': 'Tutorial',
  'Twisted': 'Twisted',
  'Two': 'Two',
  'Types': 'Types',
  'type': 'type',
  'Type': 'Type',
  'ui': 'ui',
  'Unique': 'Unique',
  'unknown': 'unknown',
  'Update': 'Update',
  'Upgrade': 'Upgrade',
  'Upsell': 'Upsell',
  'Up': 'Up',
  'Valley': 'Valley',
  'value': 'value',
  'variables': 'variables',
  'Variables': 'Variables',
  'vector': 'vector',
  'vibration': 'vibration',
  'Victory': 'Victory',
  'Viz': 'Viz',
  'Voice': 'Voice',
  'volume': 'volume',
  'Vote': 'Vote',
  'vo': 'vo',
  'Wait': 'Wait',
  'wall': 'wall',
  'Wand': 'Wand',
  'Wardrobe': 'Wardrobe',
  'Warnings': 'Warnings',
  'Warning': 'Warning',
  'Warp': 'Warp',
  'war': 'war',
  'Weapon': 'Weapon',
  'weather': 'weather',
  'Weeks': 'Weeks',
  'Weights': 'Weights',
  'Western': 'Western',
  'Wheel': 'Wheel',
  'Wield': 'Wield',
  'Windows': 'Windows',
  'wise': 'wise',
  'world': 'world',
  'World': 'World',
  'ZE': 'ZE',
  'zone': 'zone',
  'Zone': 'Zone',
};

let names = {};
let newnames = {};

fs.readFileSync('names.txt').toString().split(/\s+/gi).forEach(name => {
  names[name] = name;
});

Object.keys(names).forEach(name => {
  let matches = name.split(/^((?:fl|u|n|s|sz|pt|t|m|a|ar|b|bc|dw|e|f|gbid|h|i|is|id|l|p|pn|q|v|vw|wd|wp|wr|ws|wv)(?=[0-9A-Z_]))/g).filter(Boolean);

  matches.forEach(subname => {
    if (/^[^a-zA-Z]+$/.test(subname)) {
      return;
    }

    if (/^(fl|u|n|s|sz|pt|t|m|a|ar|b|bc|dw|e|f|gbid|h|i|is|id|l|p|pn|q|v|vw|wd|wp|wr|ws|wv)$/g.test(subname)) {
      prefix[subname] = names[name];
    } else {
      newnames[subname] = names[name];
    }
  });
});

names = newnames;
newnames = {};

Object.keys(names).forEach(name => {
  let matches = name.split(/(3x3|4x4|BCVEC2I|IDs(?![a-z])|By(?![a-z])|To(?![a-z])|In(?![a-z])|Is(?![a-z])|On(?![a-z])|No(?![a-z])|(?<![0-9])2D|(?<![0-9])3D|(?<![0-9])4D)/g).filter(Boolean);

  matches.forEach(subname => {
    if (/^([^a-zA-Z]+)$/.test(subname)) {
      return;
    }

    if (/^(3x3|4x4|BCVEC2I|IDs(?![a-z])|By(?![a-z])|To(?![a-z])|In(?![a-z])|Is(?![a-z])|On(?![a-z])|No(?![a-z])|(?<![0-9])2D|(?<![0-9])3D|(?<![0-9])4D)$/g.test(subname) || /^[a-z]{3,}$/g.test(subname)) {
      dict[subname] = names[name];
    } else {
      newnames[subname] = names[name];
    }
  });
});

names = newnames;
newnames = {};

Object.keys(names).forEach(name => {
  let matches = name.split(/([A-Z][a-z]{2,})/g).filter(Boolean);

  matches.forEach(subname => {
    if (/^[^a-zA-Z]+$/.test(subname)) {
      return;
    }

    if (/^([A-Z][a-z]+)$/g.test(subname) || /^[a-z]{3,}$/g.test(subname)) {
      dict[subname] = names[name];
    } else {
      newnames[subname] = names[name];
    }
  });
});

names = newnames;
newnames = {};

Object.keys(names).forEach(name => {
  let matches = name.split(/([A-Z]{2,})/g).filter(Boolean);

  matches.forEach(subname => {
    if (/^[^a-zA-Z]+$/.test(subname)) {
      return;
    }

    if (/^([A-Z]{2,})$/g.test(subname) || /^[a-z]{3,}$/g.test(subname)) {
      dict[subname] = names[name];
    } else {
      newnames[subname] = names[name];
    }
  });
});

names = newnames;
newnames = {};

Object.keys(names).forEach(name => {
  let matches = name.split(/_+/g).filter(Boolean);

  matches.forEach(subname => {
    if (subname.length > 1 && !/^[^a-z]+$/gi.test(subname)) {
      newnames[subname] = names[name];
    }
  });
});

names = newnames;
newnames = {};

Object.keys(names).forEach(name => {
  let matches = name.split(/([a-z]+[0-9]*)/g).filter(Boolean);

  matches.forEach(subname => {
    if (subname.length > 1 && !/^[^a-z]+$/gi.test(subname)) {
      dict[subname] = names[name];
    }
  });
});

names = newnames;
newnames = {};

prefix = Object.keys(prefix).sort();
dict = Object.keys(dict).sort();

fs.writeFileSync('prefix.txt', prefix.join('\n'));
fs.writeFileSync('dict.txt', dict.join('\n'));

fs.writeFileSync('dict.h', [
  '#include <string>',
  '#include <vector>',
  '',
  'std::vector<std::string> getPrefixes() {',
  '  std::vector<std::string> ret;',
  ...prefix.map((v, i) => '  ret.push_back(' + JSON.stringify(v) + '); // ' + i),
  '  return ret;',
  '};',
  '',
  'std::vector<std::string> getDict() {',
  '  std::vector<std::string> ret;',
  ...dict.map((v, i) => '  ret.push_back(' + JSON.stringify(v) + '); // ' + i),
  '  return ret;',
  '};',
  '',
].join('\n'));
