/**
 * Definition: ActorMonsterData
 * Hash: 2f81f05b
 */

#include "ActorMonsterData.h"

void ActorMonsterData::read(const char* base, char* &ptr) {
  char *current;
  current = ptr + 0x0;
  readData(&eGender, base, current);
  current = ptr + 0x4;
  readData(&fIsNPC, base, current);
  current = ptr + 0x8;
  readData(&unk_7c902e4, base, current);
  current = ptr + 0xc;
  readData(&unk_ac5481c, base, current);
  current = ptr + 0x10;
  readData(&unk_59a87ea, base, current);
  current = ptr + 0x14;
  readData(&unk_ac1cb2e, base, current);
  current = ptr + 0x18;
  readData(&unk_765a638, base, current);
  current = ptr + 0x1c;
  readData(&unk_32c6d80, base, current);
  current = ptr + 0x40;
  readData(&eHirelingClass, base, current);
  current = ptr + 0x44;
  readData(&unk_91ce34f, base, current);
  current = ptr + 0x48;
  readData(&unk_6bce993, base, current);
  current = ptr + 0x58;
  readData(&unk_6b4a81d, base, current);
  current = ptr + 0x5c;
  readData(&snoMonsterFamily, base, current);
  current = ptr + 0x60;
  readData(&szArchetype, base, current);
  current = ptr + 0x64;
  readData(&eBaseElement, base, current);
  current = ptr + 0x68;
  readData(&snoMainHand, base, current);
  current = ptr + 0x6c;
  readData(&snoOffHand, base, current);
  current = ptr + 0x70;
  readData(&tLevelScaling, base, current);
  current = ptr + 0x80;
  readData(&nGoldGranted, base, current);
  current = ptr + 0x84;
  readData(&snoTreasureClass, base, current);
  current = ptr + 0x88;
  readData(&unk_fe8fc24, base, current);
  current = ptr + 0x8c;
  readData(&unk_681033, base, current);
  current = ptr + 0x90;
  readData(&flSummonLifetime, base, current);
  current = ptr + 0x94;
  readData(&nSummonMaxConcurrent, base, current);
  current = ptr + 0x98;
  readData(&nSummonMaxTotal, base, current);
  current = ptr + 0x9c;
  readData(&arAIBehaviors, base, current);
  current = ptr + 0xb4;
  readData(&bKillSummonsOnDeath, base, current);
  current = ptr + 0xb8;
  readData(&snoSummonActor, base, current);
  current = ptr + 0xd0;
  readData(&unk_25bcd9e, base, current);
  current = ptr + 0xe0;
  readData(&snoAffixes, base, current);
  current = ptr + 0xf0;
  readData(&unk_c8306c, base, current);
  current = ptr + 0x110;
  readData(&snoDisallowedAffixes, base, current);
  current = ptr + 0x120;
  readData(&eAITargetStyleNormal, base, current);
  current = ptr + 0x124;
  readData(&unk_67e18ba, base, current);
  current = ptr + 0x128;
  readData(&unk_130279f, base, current);
  current = ptr + 0x12c;
  readData(&unk_4b9e5c9, base, current);
  current = ptr + 0x130;
  readData(&unk_e7a2637, base, current);
  current = ptr + 0x134;
  readData(&szInternalName, base, current);
  current = ptr + 0x1b4;
  readData(&unk_d3dddc4, base, current);
  current = ptr + 0x1b8;
  readData(&unk_50569ba, base, current);
  current = ptr + 0x1bc;
  readData(&unk_7a3dc4a, base, current);
  current = ptr + 0x1c0;
  readData(&snoMount, base, current);
  current = ptr + 0x1c4;
  readData(&unk_bdcea76, base, current);
  current = ptr + 0x1c8;
  readData(&unk_87dbd3a, base, current);
  current = ptr + 0x1cc;
  readData(&unk_7859c5b, base, current);
  current = ptr + 0x1d0;
  readData(&unk_6c2321d, base, current);
  current = ptr + 0x1d4;
  readData(&unk_bc58cee, base, current);
  current = ptr + 0x1d8;
  readData(&unk_7fdab9c, base, current);
  current = ptr + 0x1dc;
  readData(&unk_e7ee8f1, base, current);
  current = ptr + 0x1e0;
  readData(&unk_e4c90d3, base, current);
  current = ptr + 0x1e4;
  readData(&unk_12ecd6a, base, current);
  current = ptr + 0x1e8;
  readData(&unk_be45ce0, base, current);
  current = ptr + 0x1ec;
  readData(&unk_db6a7c7, base, current);
  current = ptr + 0x1f0;
  readData(&unk_c2cc767, base, current);
  current = ptr + 0x1f4;
  readData(&snoStaggerPower, base, current);
  current = ptr + 0x1f8;
  readData(&unk_5c533ce, base, current);
  current = ptr + 0x1fc;
  readData(&unk_33c346f, base, current);
  current = ptr + 0x200;
  readData(&unk_1627b04, base, current);
  current = ptr + 0x204;
  readData(&unk_401e0d6, base, current);
  current = ptr + 0x208;
  readData(&unk_401dfd8, base, current);
  current = ptr + 0x20c;
  readData(&unk_f68cd00, base, current);
  current = ptr + 0x210;
  readData(&unk_f68cc02, base, current);
  current = ptr + 0x214;
  readData(&unk_16266ca, base, current);
  current = ptr + 0x218;
  readData(&unk_5428a5e, base, current);
  current = ptr + 0x21c;
  readData(&unk_3b9132c, base, current);
  current = ptr + 0x220;
  readData(&unk_c0cc954, base, current);
  current = ptr + 0x224;
  readData(&unk_d5178b2, base, current);
  current = ptr + 0x228;
  readData(&unk_e08f0df, base, current);
  ptr += 0x230;
}
