/**
 * Definition: ParticleDefinition
 * Hash: 7fe2e83d
 */

#include "ParticleDefinition.h"

void ParticleDefinition::read(const char* base, char* &ptr) {
  char *current;
  current = ptr + 0x8;
  readData(&eType, base, current);
  current = ptr + 0xc;
  readData(&dwFlags, base, current);
  current = ptr + 0x10;
  readData(&dwFlagsEx, base, current);
  current = ptr + 0x14;
  readData(&unk_75794f7, base, current);
  current = ptr + 0x18;
  readData(&tSystemDuration, base, current);
  current = ptr + 0x1c;
  readData(&tOutroDuration, base, current);
  current = ptr + 0x20;
  readData(&tPrepumpDuration, base, current);
  current = ptr + 0x24;
  readData(&eRenderDistance, base, current);
  current = ptr + 0x28;
  readData(&unk_d59152e, base, current);
  current = ptr + 0x2c;
  readData(&tSystemDurationScalar, base, current);
  current = ptr + 0x50;
  readData(&pathSystemScale, base, current);
  current = ptr + 0x60;
  readData(&pathSystemCount, base, current);
  current = ptr + 0x70;
  readData(&unk_63560e2, base, current);
  current = ptr + 0x80;
  readData(&pathSystemAlpha, base, current);
  current = ptr + 0x90;
  readData(&unk_4acb006, base, current);
  current = ptr + 0xa0;
  readData(&pathParticleDuration, base, current);
  current = ptr + 0xb0;
  readData(&pathInitialScale, base, current);
  current = ptr + 0xc0;
  readData(&pathInitialSourceRelativeSpread, base, current);
  current = ptr + 0xd0;
  readData(&pathInitialSourceRelativeVelocity, base, current);
  current = ptr + 0xe0;
  readData(&pathInitialWorldRelativeVelocity, base, current);
  current = ptr + 0xf0;
  readData(&unk_8535190, base, current);
  current = ptr + 0x100;
  readData(&pathSystemSpawnRate, base, current);
  current = ptr + 0x110;
  readData(&pathSystemSpeedSpawnRate, base, current);
  current = ptr + 0x120;
  readData(&pathSystemSpeedDurationFactor, base, current);
  current = ptr + 0x130;
  readData(&unk_e44919, base, current);
  current = ptr + 0x140;
  readData(&unk_5e70a3d, base, current);
  current = ptr + 0x150;
  readData(&unk_f627bde, base, current);
  current = ptr + 0x160;
  readData(&unk_475af70, base, current);
  current = ptr + 0x170;
  readData(&unk_79fc11d, base, current);
  current = ptr + 0x180;
  readData(&unk_24aa41d, base, current);
  current = ptr + 0x190;
  readData(&snoMaterial, base, current);
  current = ptr + 0x194;
  readData(&snoHoudini, base, current);
  current = ptr + 0x198;
  readData(&snoPhysics, base, current);
  current = ptr + 0x19c;
  readData(&unk_172022, base, current);
  current = ptr + 0x1a0;
  readData(&unk_72a45fa, base, current);
  current = ptr + 0x1a4;
  readData(&flWindFactor, base, current);
  current = ptr + 0x1a8;
  readData(&flExplosionFactor, base, current);
  current = ptr + 0x1ac;
  readData(&unk_a90d991, base, current);
  current = ptr + 0x1b0;
  readData(&flMass, base, current);
  current = ptr + 0x1b4;
  readData(&dwMaxSystems, base, current);
  current = ptr + 0x1b8;
  readData(&unk_12ce589, base, current);
  current = ptr + 0x1bc;
  readData(&flClutterZOffset, base, current);
  current = ptr + 0x1c0;
  readData(&snoActor, base, current);
  current = ptr + 0x1c4;
  readData(&tLookLink, base, current);
  current = ptr + 0x1c8;
  readData(&unk_6c0cb90, base, current);
  current = ptr + 0x1cc;
  readData(&unk_fabd80a, base, current);
  current = ptr + 0x1e0;
  readData(&ptEmitter, base, current);
  current = ptr + 0x1f8;
  readData(&pathParticleColor, base, current);
  current = ptr + 0x208;
  readData(&unk_a748ce7, base, current);
  current = ptr + 0x218;
  readData(&pathParticleAlpha, base, current);
  current = ptr + 0x228;
  readData(&pathParticleAlphaAux, base, current);
  current = ptr + 0x238;
  readData(&unk_ed6436f, base, current);
  current = ptr + 0x248;
  readData(&unk_68b6b45, base, current);
  current = ptr + 0x258;
  readData(&pathParticleScale, base, current);
  current = ptr + 0x268;
  readData(&unk_b92bb9a, base, current);
  current = ptr + 0x278;
  readData(&pathAngularPosition, base, current);
  current = ptr + 0x288;
  readData(&pathAngularVelocity, base, current);
  current = ptr + 0x298;
  readData(&pathOrientationVelocity, base, current);
  current = ptr + 0x2a8;
  readData(&unk_2d865ba, base, current);
  current = ptr + 0x2b8;
  readData(&pathOrientationPosition, base, current);
  current = ptr + 0x2c8;
  readData(&unk_8c4fe0, base, current);
  current = ptr + 0x2d8;
  readData(&pathOrientationAxis, base, current);
  current = ptr + 0x2e8;
  readData(&unk_a68a7e0, base, current);
  current = ptr + 0x2f8;
  readData(&unk_a8c5217, base, current);
  current = ptr + 0x308;
  readData(&pathMotionCylinderRadialPos, base, current);
  current = ptr + 0x318;
  readData(&pathMotionCylinderRadialVel, base, current);
  current = ptr + 0x328;
  readData(&pathMotionCylinderAngleVel, base, current);
  current = ptr + 0x338;
  readData(&pathMotionCylinderAxis, base, current);
  current = ptr + 0x348;
  readData(&pathMotionSphereRadialPos, base, current);
  current = ptr + 0x358;
  readData(&pathMotionSphereRadialVel, base, current);
  current = ptr + 0x368;
  readData(&unk_3de401d, base, current);
  current = ptr + 0x378;
  readData(&unk_3de5852, base, current);
  current = ptr + 0x388;
  readData(&unk_3ddfeb2, base, current);
  current = ptr + 0x398;
  readData(&pathMotionRelativeCartesianPos, base, current);
  current = ptr + 0x3a8;
  readData(&pathMotionRelativeCartesianVel, base, current);
  current = ptr + 0x3b8;
  readData(&pathMotionRelativeCartesianAcc, base, current);
  current = ptr + 0x3c8;
  readData(&pathMotionAttractorVel, base, current);
  current = ptr + 0x3d8;
  readData(&pathMotionAttractorPos, base, current);
  current = ptr + 0x3e8;
  readData(&unk_15ea201, base, current);
  current = ptr + 0x3f8;
  readData(&unk_afccc6, base, current);
  current = ptr + 0x408;
  readData(&unk_8dc0a2c, base, current);
  current = ptr + 0x418;
  readData(&nFacing, base, current);
  current = ptr + 0x41c;
  readData(&eAlignment, base, current);
  current = ptr + 0x420;
  readData(&wdBoundingRadius, base, current);
  current = ptr + 0x424;
  readData(&unk_a79a409, base, current);
  current = ptr + 0x428;
  readData(&unk_daaa964, base, current);
  current = ptr + 0x42c;
  readData(&dwMinSize, base, current);
  current = ptr + 0x430;
  readData(&dwMaxSize, base, current);
  current = ptr + 0x434;
  readData(&unk_3e0459a, base, current);
  current = ptr + 0x438;
  readData(&unk_a0877a9, base, current);
  current = ptr + 0x43c;
  readData(&unk_63d7722, base, current);
  current = ptr + 0x440;
  readData(&snoVectorField, base, current);
  current = ptr + 0x444;
  readData(&unk_a4cad4f, base, current);
  current = ptr + 0x450;
  readData(&unk_817d767, base, current);
  current = ptr + 0x454;
  readData(&unk_16aecc9, base, current);
  current = ptr + 0x458;
  readData(&unk_8f7c9c1, base, current);
  current = ptr + 0x468;
  readData(&unk_cddc4fd, base, current);
  current = ptr + 0x478;
  readData(&unk_b4a20d4, base, current);
  current = ptr + 0x488;
  readData(&unk_da1d404, base, current);
  current = ptr + 0x48c;
  readData(&unk_5a7f188, base, current);
  ptr += 0x490;
}
