/**
 * Definition: PlayerClassDefinition
 * Hash: d83c8e8c
 */

#include "PlayerClassDefinition.h"

void PlayerClassDefinition::read(const char* base, char* &ptr) {
  ptr += 8;
  readData(&snoActorMale, base, ptr);
  readData(&snoActorFemale, base, ptr);
  readData(&snoInventory, base, ptr);
  readData(&unk_5efe7cd, base, ptr);
  readData(&unk_54e3531, base, ptr);
  readData(&unk_1a9d083, base, ptr);
  readData(&unk_9049600, base, ptr);
  readData(&flAttributesHitPoints, base, ptr);
  readData(&unk_81247b7, base, ptr);
  readData(&unk_9ae1b37, base, ptr);
  readData(&unk_9ae1b42, base, ptr);
  readData(&tPrimaryResource, base, ptr);
  readData(&tSecondaryResource, base, ptr);
  readData(&unk_b34fba9, base, ptr);
  readData(&flAttributesWalkSpeed, base, ptr);
  readData(&flAttributesRunSpeed, base, ptr);
  readData(&unk_4d59331, base, ptr);
  readData(&unk_7b1fc5b, base, ptr);
  readData(&unk_42b26d6, base, ptr);
  readData(&flAttributesCritPercentBase, base, ptr);
  readData(&unk_2ab0a5f, base, ptr);
  readData(&flAttributesResistFire, base, ptr);
  readData(&flAttributesResistLightning, base, ptr);
  readData(&flAttributesResistCold, base, ptr);
  readData(&flAttributesResistPoison, base, ptr);
  readData(&unk_8e812f9, base, ptr);
  readData(&flAttributesResistChill, base, ptr);
  readData(&unk_3b3eb32, base, ptr);
  readData(&unk_80a72d5, base, ptr);
  readData(&unk_39a9625, base, ptr);
  readData(&snoSkillKit, base, ptr);
  readData(&unk_456c862, base, ptr);
  readData(&unk_1d2596f, base, ptr);
  readData(&unk_f52d089, base, ptr);
  readData(&unk_943a946, base, ptr);
  readData(&unk_26564ba, base, ptr);
  readData(&unk_63df9da, base, ptr);
  readData(&unk_f5e5a05, base, ptr);
  readData(&unk_615e6b0, base, ptr);
  readData(&unk_3357193, base, ptr);
  readData(&unk_5ac89c6, base, ptr);
  readData(&unk_d2d8a65, base, ptr);
  readData(&arItemTiers, base, ptr);
  readData(&unk_a8e6837, base, ptr);
  readData(&unk_b3a4391, base, ptr);
  readData(&unk_17ee464, base, ptr);
  readData(&unk_a4bc7c3, base, ptr);
  readData(&unk_1b99fc4, base, ptr);
  readData(&unk_eab00df, base, ptr);
  readData(&unk_8979ddf, base, ptr);
  readData(&unk_a15f17d, base, ptr);
  readData(&unk_b81b6f8, base, ptr);
  readData(&unk_9d88058, base, ptr);
  readData(&unk_3c51d58, base, ptr);
  readData(&unk_c88ca1, base, ptr);
  readData(&unk_85b42dd, base, ptr);
  readData(&unk_5529fd9, base, ptr);
  readData(&unk_9da7619, base, ptr);
  readData(&unk_311f93e, base, ptr);
  readData(&unk_db15dcc, base, ptr);
  readData(&unk_480ce4d, base, ptr);
  readData(&unk_c204c1f, base, ptr);
  readData(&unk_ac2a184, base, ptr);
  readData(&unk_f9a8bfb, base, ptr);
  readData(&unk_c68960d, base, ptr);
  readData(&szNewDamageReduction, base, ptr);
  readData(&unk_f4401b8, base, ptr);
  readData(&unk_f38a271, base, ptr);
  readData(&unk_71458eb, base, ptr);
  readData(&unk_a996ec1, base, ptr);
  readData(&unk_699692c, base, ptr);
  readData(&unk_f5348c2, base, ptr);
  readData(&unk_4996ef8, base, ptr);
  readData(&unk_1052b5d, base, ptr);
  readData(&unk_a43c1cd, base, ptr);
  readData(&unk_448f16c, base, ptr);
  readData(&unk_90ba523, base, ptr);
  readData(&unk_a7e492e, base, ptr);
  readData(&unk_a0254bb, base, ptr);
}
