/**
 * Definition: PlayerClassDefinition
 * Hash: d83c8e8c
 */

#include "PlayerClassDefinition.h"

void PlayerClassDefinition::read(const char* base, char* &ptr) {
  char *current;
  current = ptr + 0x8;
  readData(&snoActorMale, base, current);
  current = ptr + 0xc;
  readData(&snoActorFemale, base, current);
  current = ptr + 0x10;
  readData(&snoInventory, base, current);
  current = ptr + 0x14;
  readData(&unk_5efe7cd, base, current);
  current = ptr + 0x18;
  readData(&unk_54e3531, base, current);
  current = ptr + 0x1c;
  readData(&unk_1a9d083, base, current);
  current = ptr + 0x20;
  readData(&unk_9049600, base, current);
  current = ptr + 0x24;
  readData(&flAttributesHitPoints, base, current);
  current = ptr + 0x28;
  readData(&unk_81247b7, base, current);
  current = ptr + 0x2c;
  readData(&unk_9ae1b37, base, current);
  current = ptr + 0x30;
  readData(&unk_9ae1b42, base, current);
  current = ptr + 0x34;
  readData(&tPrimaryResource, base, current);
  current = ptr + 0x54;
  readData(&tSecondaryResource, base, current);
  current = ptr + 0x74;
  readData(&unk_b34fba9, base, current);
  current = ptr + 0x78;
  readData(&flAttributesWalkSpeed, base, current);
  current = ptr + 0x7c;
  readData(&flAttributesRunSpeed, base, current);
  current = ptr + 0x80;
  readData(&unk_4d59331, base, current);
  current = ptr + 0x84;
  readData(&unk_7b1fc5b, base, current);
  current = ptr + 0x88;
  readData(&tFacingData, base, current);
  current = ptr + 0x94;
  readData(&flAttributesCritPercentBase, base, current);
  current = ptr + 0x98;
  readData(&unk_2ab0a5f, base, current);
  current = ptr + 0x9c;
  readData(&flAttributesResistFire, base, current);
  current = ptr + 0xa0;
  readData(&flAttributesResistLightning, base, current);
  current = ptr + 0xa4;
  readData(&flAttributesResistCold, base, current);
  current = ptr + 0xa8;
  readData(&flAttributesResistPoison, base, current);
  current = ptr + 0xac;
  readData(&unk_8e812f9, base, current);
  current = ptr + 0xb0;
  readData(&flAttributesResistChill, base, current);
  current = ptr + 0xb4;
  readData(&unk_3b3eb32, base, current);
  current = ptr + 0xb8;
  readData(&unk_80a72d5, base, current);
  current = ptr + 0xf8;
  readData(&unk_39a9625, base, current);
  current = ptr + 0xfc;
  readData(&snoSkillKit, base, current);
  current = ptr + 0x100;
  readData(&unk_456c862, base, current);
  current = ptr + 0x104;
  readData(&unk_1d2596f, base, current);
  current = ptr + 0x108;
  readData(&unk_f52d089, base, current);
  current = ptr + 0x120;
  readData(&unk_943a946, base, current);
  current = ptr + 0x124;
  readData(&unk_26564ba, base, current);
  current = ptr + 0x128;
  readData(&unk_63df9da, base, current);
  current = ptr + 0x130;
  readData(&unk_f5e5a05, base, current);
  current = ptr + 0x480;
  readData(&unk_615e6b0, base, current);
  current = ptr + 0x4b8;
  readData(&unk_3357193, base, current);
  current = ptr + 0x4d8;
  readData(&unk_5ac89c6, base, current);
  current = ptr + 0x500;
  readData(&unk_d2d8a65, base, current);
  current = ptr + 0x520;
  readData(&arItemTiers, base, current);
  current = ptr + 0x530;
  readData(&unk_a8e6837, base, current);
  current = ptr + 0x540;
  readData(&unk_b3a4391, base, current);
  current = ptr + 0x550;
  readData(&unk_17ee464, base, current);
  current = ptr + 0x554;
  readData(&unk_a4bc7c3, base, current);
  current = ptr + 0x558;
  readData(&unk_1b99fc4, base, current);
  current = ptr + 0x55c;
  readData(&unk_eab00df, base, current);
  current = ptr + 0x560;
  readData(&unk_8979ddf, base, current);
  current = ptr + 0x564;
  readData(&unk_a15f17d, base, current);
  current = ptr + 0x568;
  readData(&unk_b81b6f8, base, current);
  current = ptr + 0x56c;
  readData(&unk_9d88058, base, current);
  current = ptr + 0x570;
  readData(&unk_3c51d58, base, current);
  current = ptr + 0x574;
  readData(&unk_c88ca1, base, current);
  current = ptr + 0x578;
  readData(&unk_85b42dd, base, current);
  current = ptr + 0x57c;
  readData(&unk_5529fd9, base, current);
  current = ptr + 0x580;
  readData(&unk_9da7619, base, current);
  current = ptr + 0x584;
  readData(&unk_311f93e, base, current);
  current = ptr + 0x588;
  readData(&unk_db15dcc, base, current);
  current = ptr + 0x58c;
  readData(&unk_480ce4d, base, current);
  current = ptr + 0x590;
  readData(&unk_c204c1f, base, current);
  current = ptr + 0x594;
  readData(&unk_ac2a184, base, current);
  current = ptr + 0x598;
  readData(&unk_f9a8bfb, base, current);
  current = ptr + 0x59c;
  readData(&unk_c68960d, base, current);
  current = ptr + 0x5a0;
  readData(&szNewDamageReduction, base, current);
  current = ptr + 0x5a4;
  readData(&unk_f4401b8, base, current);
  current = ptr + 0x5a8;
  readData(&unk_f38a271, base, current);
  current = ptr + 0x5ac;
  readData(&unk_71458eb, base, current);
  current = ptr + 0x5b0;
  readData(&unk_a996ec1, base, current);
  current = ptr + 0x5b4;
  readData(&unk_699692c, base, current);
  current = ptr + 0x5b8;
  readData(&unk_f5348c2, base, current);
  current = ptr + 0x5bc;
  readData(&unk_4996ef8, base, current);
  current = ptr + 0x5c0;
  readData(&unk_1052b5d, base, current);
  current = ptr + 0x5c4;
  readData(&unk_a43c1cd, base, current);
  current = ptr + 0x5c8;
  readData(&unk_448f16c, base, current);
  current = ptr + 0x5cc;
  readData(&unk_90ba523, base, current);
  current = ptr + 0x5d0;
  readData(&unk_a7e492e, base, current);
  current = ptr + 0x5d4;
  readData(&unk_a0254bb, base, current);
  ptr += 0x5d8;
}
