/**
 * Definition: PowerDefinition
 * Hash: 14af0cb6
 */

#include "PowerDefinition.h"

void PowerDefinition::read(const char* base, char* &ptr) {
  char *current;
  current = ptr + 0x8;
  readData(&szInternalName, base, current);
  current = ptr + 0x48;
  readData(&bDefensive, base, current);
  current = ptr + 0x4c;
  readData(&unk_bd561bf, base, current);
  current = ptr + 0x50;
  readData(&unk_8dd1734, base, current);
  current = ptr + 0x58;
  readData(&arSkillTags, base, current);
  current = ptr + 0x68;
  readData(&eSkillCat, base, current);
  current = ptr + 0x6c;
  readData(&eType, base, current);
  current = ptr + 0x70;
  readData(&eCategory, base, current);
  current = ptr + 0x74;
  readData(&unk_2b4eb99, base, current);
  current = ptr + 0x78;
  readData(&unk_9a3836e, base, current);
  current = ptr + 0x7c;
  readData(&unk_49c0222, base, current);
  current = ptr + 0x80;
  readData(&unk_1450715, base, current);
  current = ptr + 0x84;
  readData(&unk_f3f3cf0, base, current);
  current = ptr + 0x88;
  readData(&unk_85472fb, base, current);
  current = ptr + 0x8c;
  readData(&unk_650bee9, base, current);
  current = ptr + 0x90;
  readData(&unk_3837f2a, base, current);
  current = ptr + 0x94;
  readData(&unk_6c6eb6b, base, current);
  current = ptr + 0x98;
  readData(&unk_c19db61, base, current);
  current = ptr + 0xb8;
  readData(&unk_9aad0d1, base, current);
  current = ptr + 0xbc;
  readData(&bIsBasicAttack, base, current);
  current = ptr + 0xc0;
  readData(&bIsPassive, base, current);
  current = ptr + 0xc4;
  readData(&unk_30531f7, base, current);
  current = ptr + 0xc8;
  readData(&unk_1229e8f, base, current);
  current = ptr + 0xcc;
  readData(&unk_1f1fcc, base, current);
  current = ptr + 0xd0;
  readData(&unk_5d52382, base, current);
  current = ptr + 0xd4;
  readData(&unk_49572b0, base, current);
  current = ptr + 0xd8;
  readData(&unk_c989719, base, current);
  current = ptr + 0xe0;
  readData(&unk_d8567e5, base, current);
  current = ptr + 0xf0;
  readData(&unk_d5c4ed2, base, current);
  current = ptr + 0xf4;
  readData(&unk_4d873ef, base, current);
  current = ptr + 0xf8;
  readData(&unk_fead6c5, base, current);
  current = ptr + 0xfc;
  readData(&unk_fca3b69, base, current);
  current = ptr + 0x100;
  readData(&unk_bf24, base, current);
  current = ptr + 0x104;
  readData(&unk_7ed23dd, base, current);
  current = ptr + 0x108;
  readData(&unk_f6cde9f, base, current);
  current = ptr + 0x10c;
  readData(&unk_99e0ced, base, current);
  current = ptr + 0x110;
  readData(&unk_bb05442, base, current);
  current = ptr + 0x114;
  readData(&unk_3616d3, base, current);
  current = ptr + 0x118;
  readData(&unk_41a3d22, base, current);
  current = ptr + 0x11c;
  readData(&unk_2df4181, base, current);
  current = ptr + 0x120;
  readData(&unk_91a127f, base, current);
  current = ptr + 0x124;
  readData(&unk_9e108ae, base, current);
  current = ptr + 0x128;
  readData(&unk_48531b6, base, current);
  current = ptr + 0x130;
  readData(&unk_723948e, base, current);
  current = ptr + 0x148;
  readData(&unk_fda753d, base, current);
  current = ptr + 0x160;
  readData(&arPhases, base, current);
  current = ptr + 0x178;
  readData(&unk_92fea1c, base, current);
  current = ptr + 0x17c;
  readData(&unk_8cdde38, base, current);
  current = ptr + 0x180;
  readData(&unk_df9a366, base, current);
  current = ptr + 0x190;
  readData(&unk_4bf03ff, base, current);
  current = ptr + 0x198;
  readData(&tAttackSpeed, base, current);
  current = ptr + 0x1b8;
  readData(&unk_6deb090, base, current);
  current = ptr + 0x1bc;
  readData(&unk_ed2bdad, base, current);
  current = ptr + 0x1c0;
  readData(&unk_d028a89, base, current);
  current = ptr + 0x1c4;
  readData(&unk_7a86b64, base, current);
  current = ptr + 0x1c8;
  readData(&eDamageType, base, current);
  current = ptr + 0x1cc;
  readData(&unk_752edeb, base, current);
  current = ptr + 0x1d0;
  readData(&unk_623da19, base, current);
  current = ptr + 0x1f0;
  readData(&unk_7cfb7ba, base, current);
  current = ptr + 0x210;
  readData(&unk_923b5fb, base, current);
  current = ptr + 0x214;
  readData(&unk_e517f6f, base, current);
  current = ptr + 0x218;
  readData(&eHitSound, base, current);
  current = ptr + 0x21c;
  readData(&unk_4d7691e, base, current);
  current = ptr + 0x228;
  readData(&unk_1a5392, base, current);
  current = ptr + 0x22c;
  readData(&unk_97eadb8, base, current);
  current = ptr + 0x230;
  readData(&unk_5e1a52d, base, current);
  current = ptr + 0x234;
  readData(&unk_3f1f0ff, base, current);
  current = ptr + 0x238;
  readData(&unk_41f8768, base, current);
  current = ptr + 0x240;
  readData(&unk_de3b427, base, current);
  current = ptr + 0x250;
  readData(&tHealthCost, base, current);
  current = ptr + 0x270;
  readData(&tChargeCost, base, current);
  current = ptr + 0x290;
  readData(&tMaxCharges, base, current);
  current = ptr + 0x2b0;
  readData(&tRechargeTime, base, current);
  current = ptr + 0x2d0;
  readData(&tCooldownTime, base, current);
  current = ptr + 0x2f0;
  readData(&unk_b26a921, base, current);
  current = ptr + 0x310;
  readData(&unk_86a6e05, base, current);
  current = ptr + 0x330;
  readData(&bTargetGroundOnly, base, current);
  current = ptr + 0x334;
  readData(&unk_fc01065, base, current);
  current = ptr + 0x338;
  readData(&unk_2ce4eb5, base, current);
  current = ptr + 0x33c;
  readData(&unk_e65bc77, base, current);
  current = ptr + 0x340;
  readData(&unk_67b65e9, base, current);
  current = ptr + 0x344;
  readData(&unk_a00c5eb, base, current);
  current = ptr + 0x348;
  readData(&unk_42057f3, base, current);
  current = ptr + 0x34c;
  readData(&unk_fbccf7, base, current);
  current = ptr + 0x350;
  readData(&unk_7cdc8cb, base, current);
  current = ptr + 0x354;
  readData(&unk_37d51de, base, current);
  current = ptr + 0x358;
  readData(&unk_be5487b, base, current);
  current = ptr + 0x35c;
  readData(&unk_66bbae7, base, current);
  current = ptr + 0x360;
  readData(&unk_5efc45c, base, current);
  current = ptr + 0x364;
  readData(&unk_b9ffd91, base, current);
  current = ptr + 0x368;
  readData(&unk_4d9cc58, base, current);
  current = ptr + 0x36c;
  readData(&unk_950971c, base, current);
  current = ptr + 0x370;
  readData(&unk_79e716a, base, current);
  current = ptr + 0x374;
  readData(&unk_ead9008, base, current);
  current = ptr + 0x378;
  readData(&unk_767809, base, current);
  current = ptr + 0x37c;
  readData(&bCastTargetAllies, base, current);
  current = ptr + 0x380;
  readData(&bCastTargetEnemies, base, current);
  current = ptr + 0x384;
  readData(&unk_7095076, base, current);
  current = ptr + 0x388;
  readData(&tCastTargetNecroCorpsesOnly, base, current);
  current = ptr + 0x3a8;
  readData(&unk_b9b985, base, current);
  current = ptr + 0x3c8;
  readData(&unk_bcdb405, base, current);
  current = ptr + 0x3cc;
  readData(&unk_6e40571, base, current);
  current = ptr + 0x3d0;
  readData(&unk_807540f, base, current);
  current = ptr + 0x3f0;
  readData(&unk_e7fc6fa, base, current);
  current = ptr + 0x410;
  readData(&unk_e96cf25, base, current);
  current = ptr + 0x414;
  readData(&unk_d8f7885, base, current);
  current = ptr + 0x418;
  readData(&unk_8d0166c, base, current);
  current = ptr + 0x41c;
  readData(&unk_1539714, base, current);
  current = ptr + 0x420;
  readData(&unk_e9ac57a, base, current);
  current = ptr + 0x424;
  readData(&unk_61e06df, base, current);
  current = ptr + 0x428;
  readData(&unk_787b722, base, current);
  current = ptr + 0x42c;
  readData(&unk_b2d506d, base, current);
  current = ptr + 0x430;
  readData(&unk_8b4e7a, base, current);
  current = ptr + 0x434;
  readData(&unk_44bbb8e, base, current);
  current = ptr + 0x438;
  readData(&tAttackRadius, base, current);
  current = ptr + 0x458;
  readData(&unk_3587b29, base, current);
  current = ptr + 0x45c;
  readData(&unk_49a1799, base, current);
  current = ptr + 0x460;
  readData(&unk_a114e2b, base, current);
  current = ptr + 0x464;
  readData(&unk_f70b0d, base, current);
  current = ptr + 0x468;
  readData(&unk_e65d245, base, current);
  current = ptr + 0x46c;
  readData(&unk_17dddfd, base, current);
  current = ptr + 0x470;
  readData(&unk_d897ba6, base, current);
  current = ptr + 0x4e8;
  readData(&unk_4d3c3c1, base, current);
  current = ptr + 0x4ec;
  readData(&unk_d2e4b3e, base, current);
  current = ptr + 0x4f0;
  readData(&unk_6714077, base, current);
  current = ptr + 0x4f4;
  readData(&bRequiresActorTarget, base, current);
  current = ptr + 0x4f8;
  readData(&unk_805ebfc, base, current);
  current = ptr + 0x4fc;
  readData(&unk_b4ad6e7, base, current);
  current = ptr + 0x500;
  readData(&unk_6fdff1, base, current);
  current = ptr + 0x504;
  readData(&unk_ea58c49, base, current);
  current = ptr + 0x508;
  readData(&unk_692752d, base, current);
  current = ptr + 0x50c;
  readData(&unk_eb84fbe, base, current);
  current = ptr + 0x510;
  readData(&bInvisibleDuring, base, current);
  current = ptr + 0x514;
  readData(&unk_31e452, base, current);
  current = ptr + 0x518;
  readData(&unk_1de20c9, base, current);
  current = ptr + 0x51c;
  readData(&bCannotDieDuring, base, current);
  current = ptr + 0x520;
  readData(&unk_636a66b, base, current);
  current = ptr + 0x524;
  readData(&unk_160bc26, base, current);
  current = ptr + 0x528;
  readData(&unk_e0369f5, base, current);
  current = ptr + 0x52c;
  readData(&unk_7a416a6, base, current);
  current = ptr + 0x530;
  readData(&arCCInfo, base, current);
  current = ptr + 0xa70;
  readData(&unk_6afae78, base, current);
  current = ptr + 0xa74;
  readData(&snoClassRequirement, base, current);
  current = ptr + 0xa78;
  readData(&snoSkillRequirement, base, current);
  current = ptr + 0xa7c;
  readData(&snoItemRequirement, base, current);
  current = ptr + 0xa80;
  readData(&unk_1b291d6, base, current);
  current = ptr + 0xa84;
  readData(&bUsableInTown, base, current);
  current = ptr + 0xa88;
  readData(&unk_f49838b, base, current);
  current = ptr + 0xa8c;
  readData(&unk_c2c995e, base, current);
  current = ptr + 0xa90;
  readData(&unk_744a4fd, base, current);
  current = ptr + 0xa94;
  readData(&unk_a8611dd, base, current);
  current = ptr + 0xa98;
  readData(&unk_365e3c2, base, current);
  current = ptr + 0xa9c;
  readData(&unk_83d96df, base, current);
  current = ptr + 0xaa0;
  readData(&unk_9aaab79, base, current);
  current = ptr + 0xaa4;
  readData(&unk_b15bf7f, base, current);
  current = ptr + 0xaa8;
  readData(&unk_8fe39cf, base, current);
  current = ptr + 0xaac;
  readData(&unk_ef10d9b, base, current);
  current = ptr + 0xab0;
  readData(&unk_ecb7a82, base, current);
  current = ptr + 0xab4;
  readData(&arCollisionSettings, base, current);
  current = ptr + 0xadc;
  readData(&fCannotLMBAssign, base, current);
  current = ptr + 0xae0;
  readData(&unk_2e3cde8, base, current);
  current = ptr + 0xae4;
  readData(&unk_fc20c9f, base, current);
  current = ptr + 0xae8;
  readData(&unk_a75e08a, base, current);
  current = ptr + 0xaec;
  readData(&unk_89134c5, base, current);
  current = ptr + 0xaf0;
  readData(&unk_2e9817a, base, current);
  current = ptr + 0xaf4;
  readData(&unk_e060ad6, base, current);
  current = ptr + 0xaf8;
  readData(&unk_800dd5a, base, current);
  current = ptr + 0xafc;
  readData(&unk_ba2924, base, current);
  current = ptr + 0xb00;
  readData(&unk_af8d69, base, current);
  current = ptr + 0xb04;
  readData(&unk_5f0639, base, current);
  current = ptr + 0xb08;
  readData(&unk_ca85a0a, base, current);
  current = ptr + 0xb0c;
  readData(&unk_159fc50, base, current);
  current = ptr + 0xb10;
  readData(&unk_cecdfc8, base, current);
  current = ptr + 0xb14;
  readData(&unk_210b5d5, base, current);
  current = ptr + 0xb18;
  readData(&unk_1c331c3, base, current);
  current = ptr + 0xb1c;
  readData(&unk_3f7ac9c, base, current);
  current = ptr + 0xb20;
  readData(&unk_36a68ce, base, current);
  current = ptr + 0xb28;
  readData(&unk_8a74e60, base, current);
  current = ptr + 0xb38;
  readData(&arBuffs, base, current);
  current = ptr + 0xb48;
  readData(&ptScriptFormulas, base, current);
  current = ptr + 0xb58;
  readData(&nFormulaCount, base, current);
  current = ptr + 0xb60;
  readData(&arPayloads, base, current);
  current = ptr + 0xb70;
  readData(&arMods, base, current);
  current = ptr + 0xb80;
  readData(&unk_d6e35f3, base, current);
  current = ptr + 0xb84;
  readData(&unk_cb067ec, base, current);
  current = ptr + 0xb88;
  readData(&unk_c5a8e20, base, current);
  current = ptr + 0xb90;
  readData(&unk_3ff871b, base, current);
  current = ptr + 0xb98;
  readData(&unk_90afe9c, base, current);
  current = ptr + 0xba8;
  readData(&unk_cd34118, base, current);
  ptr += 0xbb8;
}
