/**
 * Definition: QuestDefinition
 * Hash: 3ed1aefb
 */

#include "QuestDefinition.h"

void QuestDefinition::read(const char* base, char* &ptr) {
  char *current;
  current = ptr + 0x8;
  readData(&eQuestType, base, current);
  current = ptr + 0xc;
  readData(&unk_f88ee86, base, current);
  current = ptr + 0x10;
  readData(&unk_4c4339b, base, current);
  current = ptr + 0x14;
  readData(&unk_f522ece, base, current);
  current = ptr + 0x18;
  readData(&eRepeatType, base, current);
  current = ptr + 0x1c;
  readData(&unk_46224d, base, current);
  current = ptr + 0x20;
  readData(&unk_43f3849, base, current);
  current = ptr + 0x24;
  readData(&unk_48a2b16, base, current);
  current = ptr + 0x28;
  readData(&unk_d060a69, base, current);
  current = ptr + 0x30;
  readData(&vecStartLocation, base, current);
  current = ptr + 0x3c;
  readData(&unk_6a4ec7f, base, current);
  current = ptr + 0x40;
  readData(&unk_c2e8448, base, current);
  current = ptr + 0x48;
  readData(&unk_ff5c704, base, current);
  current = ptr + 0x54;
  readData(&unk_506369e, base, current);
  current = ptr + 0x58;
  readData(&unk_d2181f0, base, current);
  current = ptr + 0x5c;
  readData(&snoLevelArea, base, current);
  current = ptr + 0x60;
  readData(&unk_f956a05, base, current);
  current = ptr + 0x64;
  readData(&unk_14dee1b, base, current);
  current = ptr + 0x68;
  readData(&unk_c694251, base, current);
  current = ptr + 0x6c;
  readData(&unk_8881b0e, base, current);
  current = ptr + 0x70;
  readData(&dwNextUID, base, current);
  current = ptr + 0x74;
  readData(&unk_b89b77f, base, current);
  current = ptr + 0x78;
  readData(&unk_c18cabd, base, current);
  current = ptr + 0x7c;
  readData(&unk_79f6e17, base, current);
  current = ptr + 0x80;
  readData(&gbidSubzoneModifierTag, base, current);
  current = ptr + 0x84;
  readData(&unk_6199257, base, current);
  current = ptr + 0x88;
  readData(&unk_f322c3a, base, current);
  current = ptr + 0x8c;
  readData(&eBountyType, base, current);
  current = ptr + 0x90;
  readData(&unk_313dbf6, base, current);
  current = ptr + 0x94;
  readData(&unk_834fdbf, base, current);
  current = ptr + 0x98;
  readData(&unk_b83e7b1, base, current);
  current = ptr + 0x9c;
  readData(&unk_942bcdb, base, current);
  current = ptr + 0xa0;
  readData(&dwFlags, base, current);
  current = ptr + 0xa8;
  readData(&arQuestPhases, base, current);
  current = ptr + 0xc0;
  readData(&unk_1755172, base, current);
  current = ptr + 0xd0;
  readData(&unk_3367716, base, current);
  current = ptr + 0xe0;
  readData(&unk_46e3956, base, current);
  current = ptr + 0xf0;
  readData(&unk_56f8e05, base, current);
  current = ptr + 0xf8;
  readData(&unk_c47e01a, base, current);
  current = ptr + 0x108;
  readData(&unk_993f312, base, current);
  current = ptr + 0x118;
  readData(&unk_39af3bb, base, current);
  current = ptr + 0x128;
  readData(&unk_857ebd2, base, current);
  current = ptr + 0x138;
  readData(&unk_556de93, base, current);
  current = ptr + 0x148;
  readData(&arFollowers, base, current);
  current = ptr + 0x158;
  readData(&unk_219aee7, base, current);
  current = ptr + 0x168;
  readData(&unk_b9ec208, base, current);
  current = ptr + 0x178;
  readData(&unk_2aa5f20, base, current);
  current = ptr + 0x188;
  readData(&unk_b43b442, base, current);
  current = ptr + 0x198;
  readData(&gbidSurveyType, base, current);
  current = ptr + 0x19c;
  readData(&unk_b37e635, base, current);
  current = ptr + 0x1a0;
  readData(&snoAudioContext, base, current);
  current = ptr + 0x1a8;
  readData(&unk_af3a4c1, base, current);
  ptr += 0x1b8;
}
