/**
 * Definition: RopeDefinition
 * Hash: 31ddbbff
 */

#include "RopeDefinition.h"

void RopeDefinition::read(const char* base, char* &ptr) {
  char *current;
  current = ptr + 0x8;
  readData(&dwRopeFlags, base, current);
  current = ptr + 0xc;
  readData(&nWidth, base, current);
  current = ptr + 0x10;
  readData(&unk_d5039e2, base, current);
  current = ptr + 0x14;
  readData(&unk_5be6305, base, current);
  current = ptr + 0x18;
  readData(&flLength, base, current);
  current = ptr + 0x1c;
  readData(&flMass, base, current);
  current = ptr + 0x20;
  readData(&flMassTaperFactor, base, current);
  current = ptr + 0x24;
  readData(&flMassEnd, base, current);
  current = ptr + 0x28;
  readData(&fTextureRepeatCount, base, current);
  current = ptr + 0x2c;
  readData(&nRopeType, base, current);
  current = ptr + 0x30;
  readData(&unk_faa043c, base, current);
  current = ptr + 0x34;
  readData(&unk_daaa964, base, current);
  current = ptr + 0x38;
  readData(&flStiffness, base, current);
  current = ptr + 0x40;
  readData(&unk_e590d3c, base, current);
  current = ptr + 0x78;
  readData(&unk_24547d4, base, current);
  current = ptr + 0xb0;
  readData(&snoMaterial, base, current);
  current = ptr + 0xb4;
  readData(&snoPhysics, base, current);
  current = ptr + 0xb8;
  readData(&flWindFactor, base, current);
  current = ptr + 0xbc;
  readData(&unk_cc2f90c, base, current);
  current = ptr + 0xc4;
  readData(&tSystemDurationScalar, base, current);
  current = ptr + 0xe4;
  readData(&flOutroDuration, base, current);
  current = ptr + 0xe8;
  readData(&pathColorOverTime, base, current);
  current = ptr + 0x120;
  readData(&pathColorOverLength, base, current);
  current = ptr + 0x158;
  readData(&pathAlpha, base, current);
  current = ptr + 0x190;
  readData(&pathAlphaOverLength, base, current);
  current = ptr + 0x1c8;
  readData(&unk_ab00250, base, current);
  current = ptr + 0x200;
  readData(&unk_3c8d383, base, current);
  current = ptr + 0x238;
  readData(&unk_d96e4e6, base, current);
  current = ptr + 0x270;
  readData(&unk_bf2b399, base, current);
  current = ptr + 0x2a8;
  readData(&unk_abcab5e, base, current);
  current = ptr + 0x2e0;
  readData(&unk_9a3f811, base, current);
  current = ptr + 0x318;
  readData(&unk_3a6dc3c, base, current);
  current = ptr + 0x350;
  readData(&unk_5ddd86f, base, current);
  current = ptr + 0x388;
  readData(&pathWidthOverTime, base, current);
  current = ptr + 0x3c0;
  readData(&pathWidthOverLength, base, current);
  current = ptr + 0x3f8;
  readData(&pathSourcePointWorldUpMotion, base, current);
  current = ptr + 0x430;
  readData(&pathSourcePointAlongRopeMotion, base, current);
  current = ptr + 0x468;
  readData(&pathSourcePointPerpendicularMotion, base, current);
  current = ptr + 0x4a0;
  readData(&unk_fd2b7ac, base, current);
  current = ptr + 0x4d8;
  readData(&pathDestPointWorldUpMotion, base, current);
  current = ptr + 0x510;
  readData(&pathDestPointAlongRopeMotion, base, current);
  current = ptr + 0x548;
  readData(&pathDestPointPerpendicularMotion, base, current);
  current = ptr + 0x580;
  readData(&pathSeparation, base, current);
  current = ptr + 0x5b8;
  readData(&pathXAmpOverLength, base, current);
  current = ptr + 0x5f0;
  readData(&pathYAmpOverLength, base, current);
  current = ptr + 0x628;
  readData(&unk_14d71e7, base, current);
  current = ptr + 0x660;
  readData(&unk_3e97148, base, current);
  current = ptr + 0x698;
  readData(&pathFreqOverTime, base, current);
  current = ptr + 0x6d0;
  readData(&pathPhaseSpeedOverTime, base, current);
  current = ptr + 0x708;
  readData(&unk_e85eb5, base, current);
  current = ptr + 0x710;
  readData(&unk_f7381a2, base, current);
  current = ptr + 0x718;
  readData(&unk_bc10ec1, base, current);
  current = ptr + 0x720;
  readData(&unk_6a3b8c1, base, current);
  current = ptr + 0x758;
  readData(&unk_a74800e, base, current);
  current = ptr + 0x790;
  readData(&unk_a85b95c, base, current);
  current = ptr + 0x798;
  readData(&unk_910dc49, base, current);
  current = ptr + 0x7a0;
  readData(&unk_fa52de8, base, current);
  current = ptr + 0x7a8;
  readData(&unk_c44c7c8, base, current);
  current = ptr + 0x7e0;
  readData(&unk_4a82155, base, current);
  current = ptr + 0x818;
  readData(&unk_340e1fe, base, current);
  current = ptr + 0x81c;
  readData(&unk_93baab, base, current);
  current = ptr + 0x828;
  readData(&unk_9979296, base, current);
  current = ptr + 0x860;
  readData(&unk_5a2a13a, base, current);
  current = ptr + 0x898;
  readData(&unk_1d019ab, base, current);
  current = ptr + 0x8d0;
  readData(&ptMsgTriggeredEvents, base, current);
  current = ptr + 0x8e0;
  readData(&dwMaxSystems, base, current);
  ptr += 0x8e8;
}
