/**
 * Definition: t11a18e87
 * Hash: 11a18e87
 */

#include "t11a18e87.h"

void t11a18e87::read(const char* base, char* &ptr) {
  char *current;
  current = ptr + 0x0;
  readData(&nLeft, base, current);
  current = ptr + 0x4;
  readData(&nTop, base, current);
  current = ptr + 0x8;
  readData(&nWidth, base, current);
  current = ptr + 0xc;
  readData(&nHeight, base, current);
  current = ptr + 0x10;
  readData(&nRight, base, current);
  current = ptr + 0x14;
  readData(&nBottom, base, current);
  current = ptr + 0x18;
  readData(&nMaxWidth, base, current);
  current = ptr + 0x1c;
  readData(&nMaxHeight, base, current);
  current = ptr + 0x20;
  readData(&nMinWidth, base, current);
  current = ptr + 0x24;
  readData(&nMinHeight, base, current);
  current = ptr + 0x28;
  readData(&hTooltipText, base, current);
  current = ptr + 0x30;
  readData(&eTooltipTextJustify, base, current);
  current = ptr + 0x38;
  readData(&nTooltip, base, current);
  current = ptr + 0x48;
  readData(&nTooltipOffsetX, base, current);
  current = ptr + 0x4c;
  readData(&nTooltipOffsetY, base, current);
  current = ptr + 0x50;
  readData(&unk_b9b10c5, base, current);
  current = ptr + 0x54;
  readData(&unk_f68f8f5, base, current);
  current = ptr + 0x58;
  readData(&unk_f12b219, base, current);
  current = ptr + 0x5c;
  readData(&unk_bffade6, base, current);
  current = ptr + 0x60;
  readData(&dwAlpha, base, current);
  current = ptr + 0x64;
  readData(&unk_cdd5397, base, current);
  current = ptr + 0x68;
  readData(&snoShader, base, current);
  current = ptr + 0x70;
  readData(&unk_b25bd2f, base, current);
  current = ptr + 0x98;
  readData(&unk_9cf9482, base, current);
  current = ptr + 0xc0;
  readData(&unk_53346c4, base, current);
  current = ptr + 0xe8;
  readData(&unk_4c24000, base, current);
  current = ptr + 0xec;
  readData(&hImageFrame, base, current);
  current = ptr + 0xf0;
  readData(&unk_6124e57, base, current);
  current = ptr + 0xf4;
  readData(&unk_ca5933c, base, current);
  current = ptr + 0xf8;
  readData(&unk_902601b, base, current);
  current = ptr + 0xfc;
  readData(&unk_878e49e, base, current);
  current = ptr + 0x100;
  readData(&unk_bebd93b, base, current);
  current = ptr + 0x104;
  readData(&unk_7cf5f9e, base, current);
  current = ptr + 0x108;
  readData(&unk_d98fd69, base, current);
  current = ptr + 0x10c;
  readData(&unk_849b3d9, base, current);
  current = ptr + 0x110;
  readData(&unk_f9614a9, base, current);
  current = ptr + 0x114;
  readData(&unk_37cc53d, base, current);
  current = ptr + 0x118;
  readData(&unk_9025b89, base, current);
  current = ptr + 0x11c;
  readData(&unk_d547694, base, current);
  current = ptr + 0x120;
  readData(&unk_b0ab75a, base, current);
  current = ptr + 0x124;
  readData(&unk_f6e00c8, base, current);
  current = ptr + 0x128;
  readData(&unk_ab7c81f, base, current);
  current = ptr + 0x12c;
  readData(&unk_90fbd84, base, current);
  current = ptr + 0x130;
  readData(&unk_28714d, base, current);
  current = ptr + 0x134;
  readData(&unk_81bc013, base, current);
  current = ptr + 0x138;
  readData(&nInputFocusOrder, base, current);
  current = ptr + 0x13c;
  readData(&unk_cc2b674, base, current);
  current = ptr + 0x140;
  readData(&snoTiledStyle, base, current);
  current = ptr + 0x144;
  readData(&unk_d04e8cf, base, current);
  current = ptr + 0x148;
  readData(&unk_3dc9f06, base, current);
  current = ptr + 0x14c;
  readData(&unk_3dc9f07, base, current);
  current = ptr + 0x150;
  readData(&unk_438e5c1, base, current);
  current = ptr + 0x154;
  readData(&unk_d0d3583, base, current);
  current = ptr + 0x158;
  readData(&unk_bdc3d9e, base, current);
  current = ptr + 0x160;
  readData(&szOnClick, base, current);
  current = ptr + 0x170;
  readData(&unk_f19b822, base, current);
  current = ptr + 0x180;
  readData(&unk_c6ae8ed, base, current);
  current = ptr + 0x188;
  readData(&szOnDoubleClick, base, current);
  current = ptr + 0x198;
  readData(&szOnRightClick, base, current);
  current = ptr + 0x1a8;
  readData(&unk_cf724a8, base, current);
  current = ptr + 0x1b8;
  readData(&unk_1894e73, base, current);
  current = ptr + 0x1c0;
  readData(&unk_64741bf, base, current);
  current = ptr + 0x1d0;
  readData(&szOnDragStart, base, current);
  current = ptr + 0x1e0;
  readData(&szOnDrag, base, current);
  current = ptr + 0x1f0;
  readData(&unk_ae4056e, base, current);
  current = ptr + 0x200;
  readData(&bIsDragTarget, base, current);
  current = ptr + 0x208;
  readData(&unk_4530f50, base, current);
  current = ptr + 0x218;
  readData(&szOnContextMenu, base, current);
  current = ptr + 0x228;
  readData(&unk_d31cd22, base, current);
  current = ptr + 0x230;
  readData(&unk_341729d, base, current);
  current = ptr + 0x240;
  readData(&unk_3ff2282, base, current);
  current = ptr + 0x244;
  readData(&vecPivot, base, current);
  current = ptr + 0x24c;
  readData(&bMirrorX, base, current);
  current = ptr + 0x250;
  readData(&bMirrorY, base, current);
  current = ptr + 0x254;
  readData(&bNoSnap, base, current);
  current = ptr + 0x258;
  readData(&unk_93cbaa8, base, current);
  current = ptr + 0x25c;
  readData(&unk_3d55658, base, current);
  current = ptr + 0x260;
  readData(&rgbaTint, base, current);
  current = ptr + 0x264;
  readData(&unk_957cb7, base, current);
  current = ptr + 0x268;
  readData(&unk_8b9d9cf, base, current);
  current = ptr + 0x26c;
  readData(&rgbaDropShadow, base, current);
  current = ptr + 0x270;
  readData(&unk_3a57c1f, base, current);
  current = ptr + 0x274;
  readData(&unk_1e6c137, base, current);
  ptr += 0x278;
}
