/**
 * Definition: t11a18e87
 * Hash: 11a18e87
 */

#include "t11a18e87.h"

void t11a18e87::read(const char* base, char* &ptr) {
  readData(&nLeft, base, ptr);
  readData(&nTop, base, ptr);
  readData(&nWidth, base, ptr);
  readData(&nHeight, base, ptr);
  readData(&nRight, base, ptr);
  readData(&nBottom, base, ptr);
  readData(&nMaxWidth, base, ptr);
  readData(&nMaxHeight, base, ptr);
  readData(&nMinWidth, base, ptr);
  readData(&nMinHeight, base, ptr);
  readData(&hTooltipText, base, ptr);
  readData(&eTooltipTextJustify, base, ptr);
  readData(&nTooltip, base, ptr);
  readData(&nTooltipOffsetX, base, ptr);
  readData(&nTooltipOffsetY, base, ptr);
  readData(&unk_b9b10c5, base, ptr);
  readData(&unk_f68f8f5, base, ptr);
  readData(&unk_f12b219, base, ptr);
  readData(&unk_bffade6, base, ptr);
  readData(&dwAlpha, base, ptr);
  readData(&unk_cdd5397, base, ptr);
  readData(&snoShader, base, ptr);
  readData(&unk_b25bd2f, base, ptr);
  readData(&unk_9cf9482, base, ptr);
  readData(&unk_53346c4, base, ptr);
  readData(&unk_4c24000, base, ptr);
  readData(&hImageFrame, base, ptr);
  readData(&unk_6124e57, base, ptr);
  readData(&unk_ca5933c, base, ptr);
  readData(&unk_902601b, base, ptr);
  readData(&unk_878e49e, base, ptr);
  readData(&unk_bebd93b, base, ptr);
  readData(&unk_7cf5f9e, base, ptr);
  readData(&unk_d98fd69, base, ptr);
  readData(&unk_849b3d9, base, ptr);
  readData(&unk_f9614a9, base, ptr);
  readData(&unk_37cc53d, base, ptr);
  readData(&unk_9025b89, base, ptr);
  readData(&unk_d547694, base, ptr);
  readData(&unk_b0ab75a, base, ptr);
  readData(&unk_f6e00c8, base, ptr);
  readData(&unk_ab7c81f, base, ptr);
  readData(&unk_90fbd84, base, ptr);
  readData(&unk_28714d, base, ptr);
  readData(&unk_81bc013, base, ptr);
  readData(&nInputFocusOrder, base, ptr);
  readData(&unk_cc2b674, base, ptr);
  readData(&snoTiledStyle, base, ptr);
  readData(&unk_d04e8cf, base, ptr);
  readData(&unk_3dc9f06, base, ptr);
  readData(&unk_3dc9f07, base, ptr);
  readData(&unk_438e5c1, base, ptr);
  readData(&unk_d0d3583, base, ptr);
  readData(&unk_bdc3d9e, base, ptr);
  readData(&szOnClick, base, ptr);
  readData(&unk_f19b822, base, ptr);
  readData(&unk_c6ae8ed, base, ptr);
  readData(&szOnDoubleClick, base, ptr);
  readData(&szOnRightClick, base, ptr);
  readData(&unk_cf724a8, base, ptr);
  readData(&unk_1894e73, base, ptr);
  readData(&unk_64741bf, base, ptr);
  readData(&szOnDragStart, base, ptr);
  readData(&szOnDrag, base, ptr);
  readData(&unk_ae4056e, base, ptr);
  readData(&bIsDragTarget, base, ptr);
  readData(&unk_4530f50, base, ptr);
  readData(&szOnContextMenu, base, ptr);
  readData(&unk_d31cd22, base, ptr);
  readData(&unk_341729d, base, ptr);
  readData(&unk_3ff2282, base, ptr);
  readData(&vecPivot, base, ptr);
  readData(&bMirrorX, base, ptr);
  readData(&bMirrorY, base, ptr);
  readData(&bNoSnap, base, ptr);
  readData(&unk_93cbaa8, base, ptr);
  readData(&unk_3d55658, base, ptr);
  readData(&rgbaTint, base, ptr);
  readData(&unk_957cb7, base, ptr);
  readData(&unk_8b9d9cf, base, ptr);
  readData(&rgbaDropShadow, base, ptr);
  readData(&unk_3a57c1f, base, ptr);
  readData(&unk_1e6c137, base, ptr);
}
