/**
 * Definition: t1adf4e20
 * Hash: 1adf4e20
 */

#include "t1adf4e20.h"

void t1adf4e20::read(const char* base, char* &ptr) {
  char *current;
  current = ptr + 0x8;
  readData(&dwType, base, current);
  current = ptr + 0xc;
  readData(&dwPad, base, current);
  current = ptr + 0x10;
  readData(&fDisableNonFriendlyOperation, base, current);
  current = ptr + 0x14;
  readData(&fWalkToCenter, base, current);
  current = ptr + 0x18;
  readData(&unk_2387505, base, current);
  current = ptr + 0x1c;
  readData(&fUseStringListName, base, current);
  current = ptr + 0x20;
  readData(&unk_444cd69, base, current);
  current = ptr + 0x24;
  readData(&flOperationRadius, base, current);
  current = ptr + 0x28;
  readData(&unk_d0b1df5, base, current);
  current = ptr + 0x2c;
  readData(&unk_76fbf14, base, current);
  current = ptr + 0x30;
  readData(&unk_83183d4, base, current);
  current = ptr + 0x34;
  readData(&unk_2767229, base, current);
  current = ptr + 0x38;
  readData(&unk_f184557, base, current);
  current = ptr + 0x3c;
  readData(&unk_6d9ebe1, base, current);
  current = ptr + 0x40;
  readData(&unk_5456245, base, current);
  current = ptr + 0x44;
  readData(&unk_af5815a, base, current);
  current = ptr + 0x48;
  readData(&unk_18353a0, base, current);
  current = ptr + 0x4c;
  readData(&unk_11a3492, base, current);
  current = ptr + 0x50;
  readData(&unk_3e0941e, base, current);
  current = ptr + 0x54;
  readData(&tConditionData, base, current);
  current = ptr + 0x58;
  readData(&unk_bfad8a9, base, current);
  current = ptr + 0x5c;
  readData(&unk_1552d4d, base, current);
  current = ptr + 0x60;
  readData(&unk_2cf2865, base, current);
  current = ptr + 0x64;
  readData(&unk_fe76809, base, current);
  current = ptr + 0x68;
  readData(&unk_359810e, base, current);
  current = ptr + 0x6c;
  readData(&nCooldown, base, current);
  current = ptr + 0x70;
  readData(&unk_9c8478e, base, current);
  current = ptr + 0x74;
  readData(&unk_d45ed2d, base, current);
  current = ptr + 0x78;
  readData(&unk_f6b20b7, base, current);
  current = ptr + 0x7c;
  readData(&unk_54513b8, base, current);
  current = ptr + 0x80;
  readData(&unk_fd1f378, base, current);
  current = ptr + 0x84;
  readData(&unk_487c14, base, current);
  current = ptr + 0x88;
  readData(&unk_87f2609, base, current);
  current = ptr + 0x8c;
  readData(&unk_158eb4f, base, current);
  current = ptr + 0x90;
  readData(&unk_ab58cd3, base, current);
  current = ptr + 0x94;
  readData(&unk_91a3966, base, current);
  current = ptr + 0x98;
  readData(&unk_25312e5, base, current);
  current = ptr + 0x9c;
  readData(&unk_4be4371, base, current);
  current = ptr + 0xa0;
  readData(&unk_812c9e9, base, current);
  current = ptr + 0xa4;
  readData(&unk_e91141a, base, current);
  current = ptr + 0xa8;
  readData(&unk_c2ce9c, base, current);
  current = ptr + 0xac;
  readData(&unk_92ef706, base, current);
  current = ptr + 0xb0;
  readData(&unk_8131b11, base, current);
  current = ptr + 0xb4;
  readData(&unk_545c5ca, base, current);
  current = ptr + 0xb8;
  readData(&eSpawnType, base, current);
  current = ptr + 0xbc;
  readData(&unk_c005492, base, current);
  current = ptr + 0xc0;
  readData(&snoSpawnEncounter, base, current);
  current = ptr + 0xc4;
  readData(&snoPopulation, base, current);
  current = ptr + 0xc8;
  readData(&snoSpawnEffect, base, current);
  current = ptr + 0xcc;
  readData(&unk_d32ee25, base, current);
  current = ptr + 0xd0;
  readData(&unk_2820068, base, current);
  current = ptr + 0xd4;
  readData(&unk_50d7e54, base, current);
  current = ptr + 0xd8;
  readData(&snoSpawnItem, base, current);
  current = ptr + 0xdc;
  readData(&unk_59c2867, base, current);
  current = ptr + 0xe0;
  readData(&unk_6cc5610, base, current);
  current = ptr + 0xe4;
  readData(&unk_4701df7, base, current);
  current = ptr + 0xf8;
  readData(&tInstanceData, base, current);
  ptr += 0x1c8;
}
