/**
 * Definition: t24a8a9be
 * Hash: 24a8a9be
 */

#include "t24a8a9be.h"

void t24a8a9be::read(const char* base, char* &ptr) {
  char *current;
  current = ptr + 0x0;
  readData(&unk_b7593d9, base, current);
  current = ptr + 0x4;
  readData(&unk_ef17f0b, base, current);
  current = ptr + 0x8;
  readData(&unk_aec0875, base, current);
  current = ptr + 0xc;
  readData(&snoHighlight, base, current);
  current = ptr + 0x10;
  readData(&unk_c1379cf, base, current);
  current = ptr + 0x14;
  readData(&unk_eb1288f, base, current);
  current = ptr + 0x18;
  readData(&unk_5f72810, base, current);
  current = ptr + 0x1c;
  readData(&unk_49f6894, base, current);
  current = ptr + 0x20;
  readData(&unk_d434228, base, current);
  current = ptr + 0x24;
  readData(&unk_6ff7a13, base, current);
  current = ptr + 0x28;
  readData(&unk_23d51f2, base, current);
  current = ptr + 0x2c;
  readData(&snoOccluded, base, current);
  current = ptr + 0x30;
  readData(&snoDepth, base, current);
  current = ptr + 0x34;
  readData(&snoCookie, base, current);
  current = ptr + 0x38;
  readData(&snoUIRActor, base, current);
  current = ptr + 0x3c;
  readData(&unk_d2ef4a4, base, current);
  current = ptr + 0x40;
  readData(&unk_445df1d, base, current);
  current = ptr + 0x44;
  readData(&snoPowerCenters, base, current);
  current = ptr + 0x48;
  readData(&unk_a2d779a, base, current);
  current = ptr + 0x4c;
  readData(&unk_62b01b3, base, current);
  current = ptr + 0x50;
  readData(&unk_fda1e28, base, current);
  current = ptr + 0x54;
  readData(&unk_8857547, base, current);
  current = ptr + 0x58;
  readData(&unk_57fb208, base, current);
  current = ptr + 0x5c;
  readData(&unk_279eec9, base, current);
  current = ptr + 0x60;
  readData(&outputGpuBinaries, base, current);
  current = ptr + 0x64;
  readData(&unk_259e646, base, current);
  current = ptr + 0x68;
  readData(&unk_a90ec3a, base, current);
  current = ptr + 0x6c;
  readData(&unk_78b28fb, base, current);
  current = ptr + 0x70;
  readData(&unk_48565bc, base, current);
  current = ptr + 0x74;
  readData(&unk_17fa27d, base, current);
  current = ptr + 0x78;
  readData(&unk_65c301c, base, current);
  current = ptr + 0x7c;
  readData(&unk_edc70d0, base, current);
  current = ptr + 0x80;
  readData(&unk_bd6ad91, base, current);
  current = ptr + 0x84;
  readData(&unk_8d0ea52, base, current);
  current = ptr + 0x88;
  readData(&unk_fcdf27b, base, current);
  current = ptr + 0x8c;
  readData(&unk_6867f0f, base, current);
  current = ptr + 0x90;
  readData(&unk_380bbd0, base, current);
  current = ptr + 0x94;
  readData(&unk_7af891, base, current);
  current = ptr + 0x98;
  readData(&unk_d753552, base, current);
  current = ptr + 0x9c;
  readData(&unk_8c6cbe4, base, current);
  current = ptr + 0xa0;
  readData(&unk_e9a8598, base, current);
  current = ptr + 0xa4;
  readData(&unk_b94c259, base, current);
  current = ptr + 0xa8;
  readData(&unk_88eff1a, base, current);
  current = ptr + 0xac;
  readData(&unk_679d69f, base, current);
  current = ptr + 0xb0;
  readData(&unk_2aee7b3, base, current);
  current = ptr + 0xb4;
  readData(&unk_fa92474, base, current);
  current = ptr + 0xb8;
  readData(&unk_ca36135, base, current);
  current = ptr + 0xbc;
  readData(&unk_99d9df6, base, current);
  current = ptr + 0xc0;
  readData(&unk_abed88, base, current);
  current = ptr + 0xc4;
  readData(&unk_323dbbc, base, current);
  current = ptr + 0xc8;
  readData(&unk_1e187d, base, current);
  current = ptr + 0xcc;
  readData(&unk_d18553e, base, current);
  ptr += 0xd0;
}
