/**
 * Definition: tb0ba2b42
 * Hash: b0ba2b42
 */

#include "tb0ba2b42.h"

void tb0ba2b42::read(const char* base, char* &ptr) {
  char *current;
  current = ptr + 0x0;
  readData(&unk_50e1da7, base, current);
  current = ptr + 0x10;
  readData(&unk_50e1da8, base, current);
  current = ptr + 0x20;
  readData(&unk_50e1da9, base, current);
  current = ptr + 0x30;
  readData(&unk_50e1e6d, base, current);
  current = ptr + 0x40;
  readData(&unk_50e1e6e, base, current);
  current = ptr + 0x50;
  readData(&unk_50e1e6f, base, current);
  current = ptr + 0x60;
  readData(&szOnButton1, base, current);
  current = ptr + 0x70;
  readData(&szOnButton2, base, current);
  current = ptr + 0x80;
  readData(&szOnButton3, base, current);
  current = ptr + 0x90;
  readData(&szOnButton4, base, current);
  current = ptr + 0xa0;
  readData(&szOnDPadUp, base, current);
  current = ptr + 0xb0;
  readData(&szOnDPadRight, base, current);
  current = ptr + 0xc0;
  readData(&szOnDPadLeft, base, current);
  current = ptr + 0xd0;
  readData(&szOnDPadDown, base, current);
  current = ptr + 0xe0;
  readData(&szOnBack, base, current);
  current = ptr + 0xf0;
  readData(&szOnStart, base, current);
  current = ptr + 0x100;
  readData(&unk_e959ede, base, current);
  current = ptr + 0x110;
  readData(&unk_e1fae12, base, current);
  current = ptr + 0x120;
  readData(&unk_4cbd064, base, current);
  current = ptr + 0x130;
  readData(&unk_4dde8e5, base, current);
  current = ptr + 0x140;
  readData(&unk_4f00166, base, current);
  current = ptr + 0x150;
  readData(&unk_2cac42a, base, current);
  current = ptr + 0x160;
  readData(&unk_2dcdcab, base, current);
  current = ptr + 0x170;
  readData(&unk_2eef52c, base, current);
  current = ptr + 0x180;
  readData(&unk_24240f4, base, current);
  current = ptr + 0x190;
  readData(&unk_2545975, base, current);
  current = ptr + 0x1a0;
  readData(&unk_26671f6, base, current);
  current = ptr + 0x1b0;
  readData(&unk_2788a77, base, current);
  current = ptr + 0x1c0;
  readData(&unk_8d1cc85, base, current);
  current = ptr + 0x1d0;
  readData(&unk_9e50fde, base, current);
  current = ptr + 0x1e0;
  readData(&unk_e5c70eb, base, current);
  current = ptr + 0x1f0;
  readData(&unk_54f4918, base, current);
  current = ptr + 0x200;
  readData(&unk_aaebdb8, base, current);
  current = ptr + 0x210;
  readData(&szFirstActiveChild, base, current);
  current = ptr + 0x220;
  readData(&unk_c0f151b, base, current);
  current = ptr + 0x230;
  readData(&unk_3b59e4f, base, current);
  current = ptr + 0x240;
  readData(&unk_9a1cd2f, base, current);
  current = ptr + 0x244;
  readData(&unk_c7baf30, base, current);
  current = ptr + 0x248;
  readData(&unk_f559131, base, current);
  current = ptr + 0x24c;
  readData(&unk_e2699f5, base, current);
  current = ptr + 0x250;
  readData(&unk_1007bf6, base, current);
  current = ptr + 0x254;
  readData(&unk_3da5df7, base, current);
  current = ptr + 0x258;
  readData(&unk_b3c98bf, base, current);
  current = ptr + 0x25c;
  readData(&unk_e167ac0, base, current);
  current = ptr + 0x260;
  readData(&unk_f05cc1, base, current);
  current = ptr + 0x264;
  readData(&unk_3ca3ec2, base, current);
  current = ptr + 0x268;
  readData(&unk_6edded0, base, current);
  current = ptr + 0x26c;
  readData(&unk_be404a9, base, current);
  current = ptr + 0x270;
  readData(&unk_9877a36, base, current);
  current = ptr + 0x274;
  readData(&unk_f32fde3, base, current);
  current = ptr + 0x278;
  readData(&unk_b338683, base, current);
  current = ptr + 0x27c;
  readData(&unk_e016b80, base, current);
  current = ptr + 0x280;
  readData(&unk_3087066, base, current);
  current = ptr + 0x284;
  readData(&unk_3a9209a, base, current);
  current = ptr + 0x288;
  readData(&szLStickHandler, base, current);
  current = ptr + 0x298;
  readData(&unk_5e4bcce, base, current);
  current = ptr + 0x2a8;
  readData(&szRStickHandler, base, current);
  current = ptr + 0x2b8;
  readData(&unk_9b3146, base, current);
  current = ptr + 0x2c8;
  readData(&unk_69bea99, base, current);
  current = ptr + 0x2d8;
  readData(&unk_4d22020, base, current);
  current = ptr + 0x2e8;
  readData(&unk_d7b653, base, current);
  ptr += 0x2f8;
}
